"""
SQLAlchemy async models for AgentOS-Goldmine.
Tracks mining tasks, agent trace logs, trading signals, and memory entries.
"""

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import JSON, DateTime, Enum, ForeignKey, Float, String, Text, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class MiningTask(Base):
    """Represents a gold-mining request submitted by the user."""
    __tablename__ = "mining_tasks"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    symbols: Mapped[list] = mapped_column(JSON)                   # ["BTCUSDT", "ETHUSDT"]
    timeframe: Mapped[str] = mapped_column(String(10), default="1h")
    social_sources: Mapped[list] = mapped_column(JSON, default=list)
    status: Mapped[str] = mapped_column(
        Enum("pending", "running", "completed", "failed", name="task_status"),
        default="pending",
    )
    celery_task_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    # Results
    signals: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    overall_sentiment: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    confidence_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    report_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    tokens_used: Mapped[int] = mapped_column(default=0)
    execution_time_ms: Mapped[int] = mapped_column(default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())

    trace_logs: Mapped[list["AgentTraceLog"]] = relationship(
        back_populates="task", cascade="all, delete-orphan"
    )
    trading_signals: Mapped[list["TradingSignal"]] = relationship(
        back_populates="task", cascade="all, delete-orphan"
    )


class AgentTraceLog(Base):
    """Real-time log emitted by each agent during the mining pipeline."""
    __tablename__ = "agent_trace_logs"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    task_id: Mapped[str] = mapped_column(ForeignKey("mining_tasks.id", ondelete="CASCADE"))
    agent_name: Mapped[str] = mapped_column(String(50))   # TrendMiner, SentimentHarvester, etc.
    phase: Mapped[str] = mapped_column(
        Enum("plan", "reason", "act", "reflect", "error", name="log_phase")
    )
    message: Mapped[str] = mapped_column(Text)
    data: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    task: Mapped["MiningTask"] = relationship(back_populates="trace_logs")


class TradingSignal(Base):
    """A trading signal generated by GoldDigger for a specific symbol."""
    __tablename__ = "trading_signals"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    task_id: Mapped[str] = mapped_column(ForeignKey("mining_tasks.id", ondelete="CASCADE"))
    symbol: Mapped[str] = mapped_column(String(20))
    direction: Mapped[str] = mapped_column(Enum("long", "short", "neutral", name="signal_dir"))
    entry_price: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    stop_loss: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    take_profit: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rr_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    confidence: Mapped[float] = mapped_column(Float, default=0.0)
    kelly_fraction: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    sentiment_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    technical_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    reasoning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    task: Mapped["MiningTask"] = relationship(back_populates="trading_signals")
